The visibility system has changed.

BEFORE (current functionality):


** Regular Post (Default)
By default, posts are visible everywhere. No special keywords needed.

** Hidden Post Example
To hide a post completely from all listings:
#+begin_example
#+VISIBILITY: hidden
#+end_example




AFTER (desired functionality):


* Post Visibility Examples

** Regular Post (Default)
By default, posts are visible everywhere. No special keywords needed.


** Default
By default, all blog posts appear in the blog list page. This occurs if visibility is not set at all, or in this case:

#+begin_example
#+VISIBILITY: blog
#+end_example


** Hidden Post Example
To hide a post completely from all listings:
#+begin_example
#+VISIBILITY: hidden
#+end_example

** Hide From Main Blog Example  
To hide from main blog but show on tag/category pages:
#+begin_example
#+VISIBILITY: example 
#+end_example

We now need to support these outputs:

visibility: blog
visibility: hidden 
visibility: example
visibility: arbitrary-tag-or-keyword
